<!DOCTYPE html>
<html lang="ar" dir="rtl" class="js">

<head>
    <base href="../">
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="./images/favicon.png">
    <!-- Page Title  -->
    <title>Invest Dashboard | DashLite Admin Template</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="{{ asset('student_assets/css/dashlite.css?ver=2.8.0') }}">
    <link id="skin-default" rel="stylesheet" href="{{ asset('student_assets/css/theme.css?ver=2.8.0') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@460&display=swap" rel="stylesheet">


    <style>
        .nk-header.is-theme:not([class*=bg-]) {
            background: #06933e;
            border-color: #9fcda5;
        }
        .is-theme .user-name {
            color: #000000;
        }
        .is-theme .nk-menu > li > .nk-menu-link {
            color: #f5f6fa!important;
        }
        .card {
            direction : rtl;
        }
        .invest-data-history .title {
            font-size: 14px;
        }
        .subtitle{
            font-weight: bold!important;
            font-size: larger!important;
        }
        .border-gradient {
            border: 10px solid;
            border-image-slice: 1;
            border-width: 3px;
            border-radius: 12px;
        }

        .border-gradient-red {
            border-image-source: linear-gradient(to left, #e52a2e, #e52a2e);
        }
        .border-gradient-blue {
            border-image-source: linear-gradient(to left, #00afe2, #00afe2);
        }
        .border-gradient-yellow {
            border-image-source: linear-gradient(to left, #fcc400, #fcc400);
        }
        .border-gradient-green {
            border-image-source: linear-gradient(to left, #06933e, #c7c78c );
        }
        .preloader {
            align-items: center;
            background: #FFF;
            display: flex;
            height: 100vh;
            justify-content: center;
            left: 0;
            position: fixed;
            top: 0;
            transition: opacity 0.2s linear;
            width: 100%;
            z-index: 9999;
            opacity: 1;
            transform: opacity 1s linear;
        }
        .scale-in-ver-bottom {
            -webkit-animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        }
        /* ----------------------------------------------
     * Generated by Animista on 2022-5-8 20:12:3
     * Licensed under FreeBSD License.
     * See http://animista.net/license for more info.
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

        /**
         * ----------------------------------------
         * animation scale-in-ver-bottom
         * ----------------------------------------
         */
        @-webkit-keyframes scale-in-ver-bottom {
            0% {
                -webkit-transform: scaleY(0);
                transform: scaleY(0);
                -webkit-transform-origin: 0% 100%;
                transform-origin: 0% 100%;
                opacity: 1;
            }
            100% {
                -webkit-transform: scaleY(1);
                transform: scaleY(1);
                -webkit-transform-origin: 0% 100%;
                transform-origin: 0% 100%;
                opacity: 1;
            }
        }
        @keyframes scale-in-ver-bottom {
            0% {
                -webkit-transform: scaleY(0);
                transform: scaleY(0);
                -webkit-transform-origin: 0% 100%;
                transform-origin: 0% 100%;
                opacity: 1;
            }
            100% {
                -webkit-transform: scaleY(1);
                transform: scaleY(1);
                -webkit-transform-origin: 0% 100%;
                transform-origin: 0% 100%;
                opacity: 1;
            }
        }


    </style>
    <style>
        .scale-in-hor-center {
            -webkit-animation: scale-in-hor-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 2 both;
            animation: scale-in-hor-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 2 both;
        }
        /* ----------------------------------------------
     * Generated by Animista on 2022-5-5 20:32:57
     * Licensed under FreeBSD License.
     * See http://animista.net/license for more info.
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

        /**
         * ----------------------------------------
         * animation rotate-center
         * ----------------------------------------
         */
        /* ----------------------------------------------
     * Generated by Animista on 2022-5-5 20:46:12
     * Licensed under FreeBSD License.
     * See http://animista.net/license for more info.
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

        /**
         * ----------------------------------------
         * animation scale-in-hor-center
         * ----------------------------------------
         */
        @-webkit-keyframes scale-in-hor-center {
            0% {
                -webkit-transform: scaleX(0);
                transform: scaleX(0);
                opacity: 1;
            }
            100% {
                -webkit-transform: scaleX(1);
                transform: scaleX(1);
                opacity: 1;
            }
        }
        @keyframes scale-in-hor-center {
            0% {
                -webkit-transform: scaleX(0);
                transform: scaleX(0);
                opacity: 1;
            }
            100% {
                -webkit-transform: scaleX(1);
                transform: scaleX(1);
                opacity: 1;
            }
        }

        .css-selector {
            background: linear-gradient(270deg, #fcc425, #e63d2e, #1eafe2);
            background-size: 600% 600%;

            -webkit-animation: AnimationName 4s ease infinite;
            -moz-animation: AnimationName 4s ease infinite;
            animation: AnimationName 4s ease infinite;
        }

        @-webkit-keyframes AnimationName {
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }
        @-moz-keyframes AnimationName {
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }
        @keyframes AnimationName {
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }

    </style>
    <style>
        .card .table tr:first-child th, .card .table tr td{
            text-align: right;
        }
        .table th, .table td{
            vertical-align: inherit;
        }
        .dataTables_filter{
            text-align: right;
        }
        .invest-data-history{
            margin-right:  0px !important;
        }
        .arab{
            font-family: 'Cairo', sans-serif !important;

        }
    </style>
</head>
<body class="nk-body npc-invest bg-lighter ">
<div class="preloader css-selector">
    <div class="preloader-wrapper">
        <img src="{{ asset("images/preloader.png")}}" alt="logo" width="200"  />
        <p style="color: #FFF;">Plateforme des jeunes Nouaceur</p>
    </div>
</div>
<div class="nk-app-root">
    <!-- wrap @s -->
    <div class="nk-wrap ">
        <!-- main header @s -->
        <div class="nk-header nk-header-fluid is-theme" style="direction : rtl; background-image: url('https://res.cloudinary.com/dy6vgsgr8/image/upload/v1652044771/spectrum-gradient_abgkdm.png')">
            <div class="container-xl wide-xl">
                <div class="nk-header-wrap">
                    <div class="nk-menu-trigger me-sm-2 d-lg-none">
                        <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="headerNav"><em class="icon ni ni-menu"></em></a>
                    </div>
                    <div class="nk-header-brand">
                        <a href="html/index.html" class="logo-link">
                            <img style="max-height: 74px !important;" class="logo-light logo-img" src="{{ asset('images/logo_student.png') }}" srcset="./images/logo2x.png 2x" alt="logo">
                            <img style="max-height: 74px !important;" class="logo-dark logo-img" src="{{ asset('images/logo_student.png') }}" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                        </a>
                    </div><!-- .nk-header-brand -->
                    <div class="nk-header-menu" data-content="headerNav">
                        <div class="nk-header-mobile">
                            <div class="nk-header-brand">
                                <a href="html/index.html" class="logo-link">
                                    <img class="logo-light logo-img" src="./images/logo.png" srcset="./images/logo2x.png 2x" alt="logo">
                                    <img class="logo-dark logo-img" src="./images/logo-dark.png" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                                </a>
                            </div>
                            <div class="nk-menu-trigger me-n2">
                                <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="headerNav"><em class="icon ni ni-arrow-left"></em></a>
                            </div>
                        </div>
                        <ul class="nk-menu nk-menu-main ui-s2">
                            <li class="nk-menu-item has-sub">
                                <a href="#" class="nk-menu-link">
                                    <span class="nk-menu-text arab" style="font-weight: bolder; font-size: 19px;">دروس</span>
                                </a>

                            </li><!-- .nk-menu-item -->
                            <li class="nk-menu-item has-sub">
                                <a href="#" class="nk-menu-link">
                                    <span class="nk-menu-text arab" style="font-weight: bolder; font-size: 19px;">عروض العمل</span>
                                </a>

                            </li><!-- .nk-menu-item -->
                        </ul><!-- .nk-menu -->
                    </div><!-- .nk-header-menu -->
                    <div class="nk-header-tools" style="margin-right: auto; margin-left: 0">
                        <ul class="nk-quick-nav">
                            <!-- .dropdown -->
                            <li class="dropdown user-dropdown order-sm-first">
                                <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                                    <div class="user-toggle" style="flex-direction: row-reverse">
                                        <div class="user-avatar sm">
                                            <div class="nk-activity-media user-avatar bg-success"><img src="{{asset("images/avatar/a-sm.jpg")}}" alt=""></div>
                                        </div>
                                        <div class="user-info d-none d-xl-block" style="margin-right: 1rem">
                                            <div class="user-status arab" style="color: white; font-weight: bold ; font-size: 14px">الاسم و نسب</div>
{{--                                            @if($name !== null)--}}
{{--                                                <div class="user-name dropdown-indicator">{{ $name }}</div>--}}
{{--                                            @endif--}}
{{--                                        </div>--}}
                                    </div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-md dropdown-menu-end dropdown-menu-s1 is-light">
                                    <div class="dropdown-inner user-card-wrap bg-lighter d-none d-md-block">
                                        <div class="user-card">
                                            <div class="user-avatar">
                                                <span>AB</span>
                                            </div>
                                            <div class="user-info">
                                                <span class="lead-text">Abu Bin Ishtiyak</span>
                                                <span class="sub-text">info@softnio.com</span>
                                            </div>
                                            <div class="user-action">
                                                <a class="btn btn-icon me-n2" href="html/user-profile-setting.html"><em class="icon ni ni-setting"></em></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="dropdown-inner user-account-info">
                                        <h6 class="overline-title-alt">Account Balance</h6>
                                        <div class="user-balance">1,494.23 <small class="currency currency-usd">USD</small></div>
                                        <div class="user-balance-sub">Locked <span>15,495.39 <span class="currency currency-usd">USD</span></span></div>
                                        <a href="#" class="link"><span>Withdraw Balance</span> <em class="icon ni ni-wallet-out"></em></a>
                                    </div>
                                    <div class="dropdown-inner">
                                        <ul class="link-list">
                                            <li><a href="html/user-profile-regular.html"><em class="icon ni ni-user-alt"></em><span>View Profile</span></a></li>
                                            <li><a href="html/user-profile-setting.html"><em class="icon ni ni-setting-alt"></em><span>Account Setting</span></a></li>
                                            <li><a href="html/user-profile-activity.html"><em class="icon ni ni-activity-alt"></em><span>Login Activity</span></a></li>
                                            <li><a class="dark-mode-switch" href="#"><em class="icon ni ni-moon"></em><span>Dark Mode</span></a></li>
                                        </ul>
                                    </div>
                                    <div class="dropdown-inner">
                                        <ul class="link-list">
                                            <li><a href="#" id="signout"><em class="icon ni ni-signout"></em><span>Sign out</span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </li><!-- .dropdown -->
                        </ul><!-- .nk-quick-nav -->
                    </div><!-- .nk-header-tools -->
                </div><!-- .nk-header-wrap -->
            </div><!-- .container-fliud -->
        </div>
        <!-- main header @e -->
        <!-- content @s -->
        <div class="nk-content nk-content-fluid" >
            <div class="container-xl wide-xl">
                <div class="nk-content-inner">
                    <div class="nk-content-body">


                        <div class="nk-block-head nk-block-head-sm" style="direction : rtl">

                            <div class="nk-block-between">
                                <div class="nk-block-head-content">
                                    <h3 class="nk-block-title page-title arab">لوحة التحكم</h3>
                                    <div class="nk-block-des text-soft">

                                    </div>
                                </div><!-- .nk-block-head-content -->
                                <div class="nk-block-head-content">

                                </div><!-- .nk-block-head-content -->
                            </div><!-- .nk-block-between -->
                        </div><!-- .nk-block-head -->
                        <div class="nk-block">
                            <div class="row g-gs">
                                <div class="col-md-4">
                                    <div  class="card card-bordered card-full border-gradient border-gradient-red">
                                        <div class="card-inner">
                                            <div style="text-align: right;" class="card-title-group align-start mb-0">
                                                <div class="card-title">
                                                    <h6 style="color: #364a63;" class="subtitle arab">عدد الدروس المتوفرة</h6>
                                                    <span style="font-size: 54px;font-weight: bold;color:#364a63;" class="amount arab">36</span>
                                                </div>
                                                <div style="width:30%;" class="card-tools">
                                                    <img style="width: 100%;" src="{{ asset('student_assets/images/online_learning.png') }}" />
                                                </div>
                                            </div>


                                        </div>
                                    </div><!-- .card -->
                                </div><!-- .col -->
                                <div class="col-md-4">
                                    <div class="card card-bordered card-full border-gradient border-gradient-blue">
                                        <div class="card-inner">
                                            <div style="text-align: right;" class="card-title-group align-start mb-0">
                                                <div class="card-title">
                                                    <h6 style="color: #364a63;" class="subtitle arab">عدد عروض العمل</h6>
                                                    <span style="font-size: 54px;color: #364a63;font-weight: bold;color:#364a63;" class="amount arab">36</span>
                                                </div>
                                                <div style="width:30%;" class="card-tools">
                                                    <img src="{{ asset('student_assets/images/briefcase.png') }}" />
                                                </div>
                                            </div>


                                        </div>
                                    </div><!-- .card -->
                                </div><!-- .col -->
                                <div class="col-md-4">
                                    <div class="card card-bordered  card-full border-gradient border-gradient-yellow">
                                        <div class="card-inner">
                                            <div class="card-title-group align-start mb-0">
                                                <div class="card-title">
                                                    <h6 class="subtitle">الدروس التي تمت مشاهدتها</h6>
                                                    <span style="font-size: 54px;color: #364a63;font-weight: bold;color:#364a63;" class="amount arab">36</span>
                                                </div>
                                                <div style="width:30%;" class="card-tools">
                                                    <img src="{{ asset('student_assets/images/agreement.png') }}" />
                                                </div>
                                            </div>


                                        </div>
                                    </div><!-- .card -->
                                </div><!-- .col -->

                                <div class="col-lg-12">
                                    <div class="card card-bordered h-100">
                                        <div class="card-inner mb-n2">
                                            <div class="card-title-group">
                                                <div style="padding-right: 30px;" class="card-title card-title-sm">
                                                    <h6 style="font-size: larger !important;" class="title arab">معلومات عن المستخدم</h6>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="nk-tb-list is-loose">
                                            <div class="nk-tb-item nk-tb-head">
                                                <div style="font-size: 15px;font-weight: bold;" class="nk-tb-col arab"><span>الاسم و نسب</span></div>
                                                <div class="nk-tb-col text-right"><span>Users</span></div>
                                                <div style="font-size: 15px;font-weight: bold;" class="nk-tb-col"><span>السن</span></div>
                                                <div class="nk-tb-col text-right"><span>Users</span></div>
                                                <div style="font-size: 15px;font-weight: bold;" class="nk-tb-col"><span>بريد الالكتروني</span></div>
                                                <div class="nk-tb-col tb-col-sm text-right"><span>Bounce Rate</span></div>
                                                <div style="font-size: 15px;font-weight: bold;" class="nk-tb-col"><span>عنوان</span></div>
                                                <div class="nk-tb-col tb-col-sm text-right"><span>Bounce Rate</span></div>
                                                <div style="font-size: 15px;font-weight: bold;" class="nk-tb-col"><span>الهاتف</span></div>
                                                <div class="nk-tb-col tb-col-sm text-right"><span>Bounce Rate</span></div>
                                                <div style="font-size: 15px;font-weight: bold;" class="nk-tb-col"><span>تاريخ الميلاد</span></div>
                                                <div class="nk-tb-col tb-col-sm text-right"><span>Bounce Rate</span></div>
                                            </div><!-- .nk-tb-head -->

                                        </div><!-- .nk-tb-list -->
                                    </div><!-- .card -->
                                </div>
                                <div class="col-md-12 col-xxl-12">
                                    <div class="card card-bordered card-full">
                                        <div class="card-inner">

                                            <div style="text-align: right;" class="nk-block-head">
                                                <div class="nk-block-head-content">
                                                    <h4 class="nk-block-title">الدروس المتوفرة في الحساب </h4>
                                                    <div class="nk-block-des">
                                                        <p>مرحبا بك في لوحة التحكم الخاصة بالدروس المتوفرة في المنصة</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card card-preview">
                                                <div class="card-inner">
                                                    <table class="datatable-init table">
                                                        <thead>
                                                        <tr>
                                                            <th>صورة</th>
                                                            <th>اسم الدرس</th>
                                                            <th>فئة</th>
                                                            <th>الاستاذ</th>
                                                            <th>تاريخ الاضافة</th>
                                                            <th>عدد الفيديوهات</th>
                                                            <th>عدد المرفقات</th>
                                                            <th>....</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        @if(count($data) > 0)
                                                            @foreach($data as $d)
                                                                <tr>
                                                                        <td>
                                                                            <div class="nk-activity-item">
                                                                                <div style="" class="nk-activity-media user-avatar bg-success">
                                                                                    <img src="{{ asset("images/cours/". $d["photo"]) }}" alt="" />
                                                                                </div>
                                                                            </div>
                                                                        </td>
                                                                        <td>{{$d["name"]}}</td>
                                                                        <td>ostad</td>
                                                                        <td>{{ $d["created_at"] }}</td>
                                                                        <td>{{ $d["category"] }}</td>
                                                                        <td>{{ $d["videos"] }}</td>
                                                                        <td>{{ $d["modules"] }}</td>
                                                                    <td>
                                                                        <div class="dropdown">
                                                                            <a class="text-soft dropdown-toggle btn btn-sm btn-icon btn-trigger" data-toggle="dropdown" aria-expanded="false"><em class="icon ni ni-chevron-left"></em></a>
                                                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-xs" style="">
                                                                                <ul class="link-list-plain">
                                                                                    <li><a href="{{route("single_cours" , ["name" => $d["name"]])}}">عرض</a></li>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </td>
                                                                </tr>

                                                            @endforeach
                                                        @endif

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div><!-- .card-preview -->



                                        </div>
                                    </div>
                                </div><!-- .col -->



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content @e -->
        <!-- footer @s -->
        <div class="nk-footer nk-footer-fluid bg-lighter">
            <div class="container-xl">
                <div class="nk-footer-wrap">
                    <div class="nk-footer-copyright"> &copy; 2022 Platforme des jeunes nouaceur. made by <a href="#">AOBC</a>
                    </div>
                    <div class="nk-footer-links">

                    </div>
                </div>
            </div>
        </div>
        <!-- footer @e -->
    </div>
    <!-- wrap @e -->
</div>
<!-- app-root @e -->
<!-- select region modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="region">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <a href="#" class="close" data-bs-dismiss="modal"><em class="icon ni ni-cross-sm"></em></a>
            <div class="modal-body modal-body-md">
                <h5 class="title mb-4">Select Your Country</h5>
                <div class="nk-country-region">
                    <ul class="country-list text-center gy-2">
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/arg.png" alt="" class="country-flag">
                                <span class="country-name">Argentina</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/aus.png" alt="" class="country-flag">
                                <span class="country-name">Australia</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/bangladesh.png" alt="" class="country-flag">
                                <span class="country-name">Bangladesh</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/canada.png" alt="" class="country-flag">
                                <span class="country-name">Canada <small>(English)</small></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/china.png" alt="" class="country-flag">
                                <span class="country-name">Centrafricaine</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/china.png" alt="" class="country-flag">
                                <span class="country-name">China</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/french.png" alt="" class="country-flag">
                                <span class="country-name">France</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/germany.png" alt="" class="country-flag">
                                <span class="country-name">Germany</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/iran.png" alt="" class="country-flag">
                                <span class="country-name">Iran</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/italy.png" alt="" class="country-flag">
                                <span class="country-name">Italy</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/mexico.png" alt="" class="country-flag">
                                <span class="country-name">México</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/philipine.png" alt="" class="country-flag">
                                <span class="country-name">Philippines</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/portugal.png" alt="" class="country-flag">
                                <span class="country-name">Portugal</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/s-africa.png" alt="" class="country-flag">
                                <span class="country-name">South Africa</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/spanish.png" alt="" class="country-flag">
                                <span class="country-name">Spain</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/switzerland.png" alt="" class="country-flag">
                                <span class="country-name">Switzerland</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/uk.png" alt="" class="country-flag">
                                <span class="country-name">United Kingdom</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="country-item">
                                <img src="./images/flags/english.png" alt="" class="country-flag">
                                <span class="country-name">United State</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div><!-- .modal-content -->
    </div><!-- .modla-dialog -->
</div><!-- .modal -->
<!-- JavaScript -->

<script src="{{ asset('assets/js/jquery-3.5.1.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>
<!-- magnific popup js -->
<script src="{{ asset('assets/js/jquery.magnific-popup.min.js') }}"></script>
<!-- swiper js -->
<script src="{{ asset('assets/js/swiper-bundle.min.js') }}"></script>
<!-- counter js -->
<script src="{{ asset('assets/js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.counterup.min.js') }}"></script>
<!-- fullcalender js -->
<script src="{{ asset('assets/js/moment.js') }}"></script>
<script src="{{ asset('assets/js/main.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery-ui.js') }}"></script>
<!-- isotope js -->
<script src="{{ asset('assets/js/isotope.pkgd.min.js') }}"></script>
<!-- revolution slider js -->
<script src="{{ asset('assets/js/jquery.themepunch.revolution.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.themepunch.tools.min.js') }}"></script>
<!-- slider revolution extension scripts. only needed for local testing -->
<script src="{{ asset('assets/js/extensions/revolution.extension.actions.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.carousel.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.kenburn.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.layeranimation.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.migration.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.navigation.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.parallax.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.slideanims.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/revolution.extension.video.min.js') }}"></script>
<!-- form ajazchimp js -->
<script src="{{ asset('assets/js/jquery.ajaxchimp.min.js') }}"></script>
<!-- form validator js  -->
<script src="{{ asset('assets/js/form-validator.min.js') }}"></script>
<!-- contact form js -->
<script src="{{ asset('assets/js/contact-form-script.js') }}"></script>
<!-- meanmenu js -->
<script src="{{ asset('assets/js/jquery.meanmenu.min.js') }}"></script>
<!-- main js -->
<script src="{{ asset('assets/js/script.js') }}"></script>

<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<!--gellery -->


<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/js/swiper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>

<script src="{{ asset('student_assets/js/bundle.js?ver=3.0.2') }}"></script>
<script src="{{ asset('student_assets/js/scripts.js?ver=3.0.2') }}"></script>
<script src="{{ asset('student_assets/js/charts/gd-invest.js?ver=3.0.2') }}"></script>
<script src="{{ asset('student_assets/js/libs/datatable-btns.js?ver=2.8.0') }}"></script>
<script>
    let config = {
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    }
    $("#signout").on("click" , function (e) {
        e.preventDefault()
        console.log("this is nice thing")
        axios.post('/logout' , {_token : $('meta[name="csrf-token"]').attr('content') } , config).then(res => {
            if (res.status === 200){
                window.location.href = window.location.origin
            }
        })
    })
    const myPreloader = document.querySelector('.preloader');
    const fadeOutEffect = setInterval(() => {
        myPreloader.setAttribute("hidden" , "false")
        $(".card").hide()
        if (!myPreloader.style.opacity) {
            myPreloader.style.opacity = 1;
        }
        if (myPreloader.style.opacity > 0) {
            myPreloader.style.opacity -= 0.1;
        } else {
            clearInterval(fadeOutEffect);
            myPreloader.setAttribute("hidden" , "true")
            $(".card").show()
            $(".card").toggleClass("scale-in-ver-bottom")
        }
    }, 300);
    window.addEventListener('load', fadeOutEffect);
    //logout js

</script>
</body>

</html>
